module adam_mig (
    inout [15:0] ddr3_dq,
    inout [1:0] ddr3_dqs_n,
    inout [1:0] ddr3_dqs_p,
    output [14:0] ddr3_addr,
    output [2:0] ddr3_ba,
    output ddr3_ras_n,
    output ddr3_cas_n,
    output ddr3_we_n,
    output ddr3_reset_n,
    output [0:0] ddr3_ck_p,
    output [0:0] ddr3_ck_n,
    output [0:0] ddr3_cke,
    output [1:0] ddr3_dm,
    output [0:0] ddr3_odt,
    input sys_clk_i,
    input clk_ref_i,
    output ui_clk,
    output ui_clk_sync_rst,
    output ui_addn_clk_0,
    output ui_addn_clk_1,
    output ui_addn_clk_2,
    output ui_addn_clk_3,
    output ui_addn_clk_4,
    output mmcm_locked,
    input aresetn,
    input app_sr_req,
    input app_ref_req,
    input app_zq_req,
    output app_sr_active,
    output app_ref_ack,
    output app_zq_ack,
    input [1:0] s_axi_awid,
    input [28:0] s_axi_awaddr,
    input [7:0] s_axi_awlen,
    input [2:0] s_axi_awsize,
    input [1:0] s_axi_awburst,
    input [0:0] s_axi_awlock,
    input [3:0] s_axi_awcache,
    input [2:0] s_axi_awprot,
    input [3:0] s_axi_awqos,
    input s_axi_awvalid,
    output s_axi_awready,
    input [127:0] s_axi_wdata,
    input [15:0] s_axi_wstrb,
    input s_axi_wlast,
    input s_axi_wvalid,
    output s_axi_wready,
    input s_axi_bready,
    output [1:0] s_axi_bid,
    output [1:0] s_axi_bresp,
    output s_axi_bvalid,
    input [1:0] s_axi_arid,
    input [28:0] s_axi_araddr,
    input [7:0] s_axi_arlen,
    input [2:0] s_axi_arsize,
    input [1:0] s_axi_arburst,
    input [0:0] s_axi_arlock,
    input [3:0] s_axi_arcache,
    input [2:0] s_axi_arprot,
    input [3:0] s_axi_arqos,
    input s_axi_arvalid,
    output s_axi_arready,
    input s_axi_rready,
    output [1:0] s_axi_rid,
    output [127:0] s_axi_rdata,
    output [1:0] s_axi_rresp,
    output s_axi_rlast,
    output s_axi_rvalid,
    output init_calib_complete,
    output [11:0] device_temp,
    input sys_rst
);

endmodule
